name: Build LaTeX document
on: 
  push:
    paths:
      - 'latex/**'
    #    branches:
      #  - main
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: latex/main.pdf

  commit_pdf:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download PDF file
        uses: actions/download-artifact@v3
        with:
          name: PDF
      - name: Rename and Relocate PDF
        run: mv latex/main.pdf ./A-Deep-Learning-approach-for-Time-Series-Imputation-on-Photovoltaic-data.pdf
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: A-Deep-Learning-approach-for-Time-Series-Imputation-on-Photovoltaic-data.pdf
          message: 'Aggiornato PDF'
