name: Build LaTeX document
on: 
  push:
    paths:
      - 'latex/**'
      - '.github/workflows/build.yml'
    #    branches:
      #  - main
  
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: LaTeX linter (chktex)
        continue-on-error: true
        uses: j2kun/chktex-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document - Thesis
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/thesis
          root_file: main.tex
          #latexmk_use_lualatex: true
          docker_image: ghcr.io/xu-cheng/texlive-full:latest
      - name: Compile LaTeX document - Presentation
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/presentation
          root_file: main.tex
          latexmk_use_lualatex: true
          docker_image: ghcr.io/xu-cheng/texlive-full:latest

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFT
          path: latex/thesis/main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFP
          path: latex/presentation/main.pdf

  commit_pdf:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download PDF file
        uses: actions/download-artifact@v3
        with:
          name: PDFT
      - name: Rename PDF
        run: mv main.pdf A-Deep-Learning-approach-for-Time-Series-Imputation-on-Photovoltaic-data.pdf

      - name: Download PDF file
        uses: actions/download-artifact@v3
        with:
          name: PDFP
      - name: Rename PDF
        run: mv main.pdf Presentation.pdf

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '["A-Deep-Learning-approach-for-Time-Series-Imputation-on-Photovoltaic-data.pdf", "Presentation.pdf"]'
          message: 'Aggiornati PDF'
